language: cpp
os:
- linux
- osx
compiler:
- clang
- gcc

before_install:
   - sudo apt-get update -q
   - sudo apt-get install libnuma-dev bison

before_script:
   -  make -f run_configure.mk SPEC=${TRAVIS_OS_NAME}_x86-64 OMRGLUE=./example/glue all

script:
   -  make && make test
